-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgugsOgQKuQ3/O95SQ
ob/7POWeHd7BROs2dxYrcXeQnZugCgYIKoZIzj0DAQehRANCAARHFFeGWUNrOGiS
7bWFk1pAyt+mTFUKD98zgYIzLpvu8PuQGbzcoWnR3FMbwK2OxbLPWhi+l4eP9TR2
PBvCNS45
-----END PRIVATE KEY-----